version: '2.2'

services:
  kozipipe:
    build: .
    volumes:
      - "./db:/db"
    restart: on-failure

  nginx:
    build: nginx
    ports:
      - "9999:80"
    volumes:
      - "./public:/public"
    restart: on-failure
    depends_on: [kozipipe]
